version: '3.5'

services:
  rides_web:
    build: .
    image: rides:latest
    container_name: rides_container
    command: python server.py
    restart: always
    environment:
      - TEAM_NAME=CC_0113_0221_0913_1125
    ports:
      - "80:5000"
