version: '3.5'

services:
  rides_web:
    build: .
    image: rides:latest
    container_name: rides_container
    command: python server.py
    restart: always
    networks:
      - rides-network
    environment:
      - TEAM_NAME=CC_0113_0221_0913_1125
    ports:
      - "8080:5000"

networks:
  rides-network:
    external:
      name: cc_network