version: '3.5'

services:
  rmq:
    image: rabbitmq:3.8.3-alpine
    container_name: rmq_container
    networks:
      - orch-network
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - TEAM_NAME=CC_0113_0221_0913_1125
    command: rabbitmq-plugins enable rabbitmq_management

  orchestrator:
    image: orch:latest
    container_name: orch_container
    networks:
      - orch-network
    ports:
      - "8000:5000"
    environment:
      - TEAM_NAME=CC_0113_0221_0913_1125
    command: sh -c "python zk_orch.py"
    volumes:
        - .:/code
    depends_on:
        - rmq
    restart: on-failure

networks:
  orch-network:
    external:
      name: cc_network