version: '3'

services:
  web:
    image: ride:latest
    command: python server.py
    restart: always
    ports:
      - "8000:5000"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2
