version: '3'

services:
  web:
    image: rides:latest
    container_name: rides_container
    command: python server.py
    restart: always
    environment:
      - TEAM_NAME=CC_0113_0221_0913_1125
    networks:
      - rides_network
  nginx:
    image: nginx:stable
    container_name: rides_nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TEAM_NAME=CC_0113_0221_0913_1125
    ports:
      - "80:80"
    networks:
      - rides_network
  mongodb:
    image: mongo:4.2
    container_name: rides_db_container
    networks:
      - rides_network
    environment:
      - TEAM_NAME=CC_0113_0221_0913_1125
networks:
  rides_network: