version: '3'

services:
  web:
    image: rides:latest
    container_name: rides_container
    command: python server.py
    restart: always
    environment:
      - TEAM_NAME=CC_0113_0221_0913_1125
    depends_on:
      - mongodb
    ports:
      - "80:5000"
  mongodb:
    image: mongo:4.2
    container_name: rides_db_container
    environment:
      - TEAM_NAME=CC_0113_0221_0913_1125
